<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG7kmL4g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG7kmL4g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG7kmL4g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG7kmL4g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG7kmL4g\App_KernelDevDebugContainer([
    'container.build_hash' => 'G7kmL4g',
    'container.build_id' => 'dfd2cd3e',
    'container.build_time' => 1702310571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG7kmL4g');
