<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXf9H0mx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXf9H0mx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXf9H0mx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXf9H0mx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXf9H0mx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xf9H0mx',
    'container.build_id' => '8a02a343',
    'container.build_time' => 1702565731,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXf9H0mx');
