<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container102YcWX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container102YcWX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container102YcWX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container102YcWX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container102YcWX\App_KernelDevDebugContainer([
    'container.build_hash' => '102YcWX',
    'container.build_id' => 'c5c18879',
    'container.build_time' => 1702332805,
], __DIR__.\DIRECTORY_SEPARATOR.'Container102YcWX');
